### ISSUE TITLE
back buttons crash the app

### ISSUE THREAD

**Issue by jacob-hegna** [Team-A-Prime/Project-2#4]
Here is the backtrace:

> Program received signal SIGFPE, Arithmetic exception.
0x00007ffff623bd29 in pthread_barrier_destroy (barrier=0x555555af6b10)
    at pthread_barrier_destroy.c:40
40	pthread_barrier_destroy.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff623bd29 in pthread_barrier_destroy (barrier=0x555555af6b10)
    at pthread_barrier_destroy.c:40
#1  0x00007fffddee4134 in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#2  0x00007fffddef2021 in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#3  0x00007fffddbc330f in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#4  0x00007fffddbc33a5 in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#5  0x00007fffddbbf257 in ?? ()
   from /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#6  0x00007ffff6490a42 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#7  0x00007ffff646a4f6 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#8  0x00007ffff646a579 in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#9  0x00007ffff646a6ce in ?? () from /usr/lib/x86_64-linux-gnu/libGL.so.1
#10 0x00007ffff3035e22 in XCloseDisplay ()
   from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007fffef3157bf in QXcbConnection::~QXcbConnection() ()
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#12 0x00007fffef315b99 in QXcbConnection::~QXcbConnection() ()
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#13 0x00007fffef3175f6 in QXcbIntegration::~QXcbIntegration() ()
---Type <return> to continue, or q <return> to quit---
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#14 0x00007fffef3176f9 in QXcbIntegration::~QXcbIntegration() ()
   from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#15 0x00007ffff6f243cd in QGuiApplicationPrivate::~QGuiApplicationPrivate() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007ffff76e7da9 in QApplicationPrivate::~QApplicationPrivate() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff69a4d23 in QObject::~QObject() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff6970eb6 in QCoreApplication::~QCoreApplication() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007ffff76e9ec9 in QApplication::~QApplication() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00005555555599b5 in main ()

**Comment by jacob-hegna** [comment]
Debian 8, g++ 7.2

**Comment by benhaney** [comment]
Don't use back buttons
