### ISSUE TITLE
Transfer times between dates

### ISSUE THREAD

**Issue by benhaney** [Team-A-Prime/Project-2#6]
When creating a new event, the creator should be able to copy all the selected time slots from one day to any other day.

I have no idea how we should implement this

**Comment by jacob-hegna** [comment]
I plan to have a button that will just copy all the times from the first day to the others. Does this sound like what we want?

**Comment by benhaney** [comment]
sounds fine to me

**Comment by jacob-hegna** [comment]
Commit 9ed7efa adds this functionality. It doesn't let you pick that target and destination dates, however, it just always copies the times from the first date to the rest of them. Does this satisfy the requirement, in your opinion?

**Comment by benhaney** [comment]
Looked at what other groups are doing and yeah, that seems to be good enough
